name: Update README with Wallpapers

on:
  push:
    paths:
      - 'wallpapers/**'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate README
      run: |
        echo "# Wallpapers" > README.md
        for file in wallpapers/*; do
          filename=$(basename -- "$file")
          title="${filename%.*}"
          echo "## ${title}" >> README.md
          echo "![${title}](wallpapers/${filename})" >> README.md
          echo "" >> README.md
        done

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add README.md
        git commit -m 'Update README with new wallpapers'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}